// Teste das requisições REST dos prestadores
@baseURL = http://localhost:4000/api/prestadores/

// GET - lista todos os registros
GET {{baseURL}}
Content-Type: application/json

###
// GET - lista um registro pelo id
GET {{baseURL}}/64ff2674c60419442f48c8b5
Content-Type: application/json
###
// DELETE - Apaga um registro pelo id
DELETE {{baseURL}}/64ff2674c60419442f48c8b5
Content-Type: application/json

###
// POST - Insere um novo prestador
POST {{baseURL}}
Content-Type: application/json

{
    "cnpj": "13254635166123",
    "razao_social": "Strogonoff Açucarado",
    "cnae_fiscal": 451510,
    "nome_fantasia": "JOSUÉ BOY",
    "data_inicio_atividade": "2020-08-01",
    "localizacao": {
        "type": "Point",
        "coordinates":[-23.2904, -47.2963]
    }
}
